// Build the standalone SDK from the same engine.js the site runs.
//
//   node scripts/build-sdk.mjs          -> dist/mlbottleneck-engine.mjs (ESM)
//                                          dist/mlbottleneck-engine.umd.js (script tag / CommonJS)
//                                          dist/mlbottleneck-engine.d.ts (types)
//                                          dist/localmaxxing-snapshot.json (optional evidence)
//
// The engine is wrapped in a factory so each createEngine() call owns its own
// evidence cache; nothing in engine.js touches the DOM (an integrity test
// enforces that), so the wrapped source runs in Node, browsers, and workers.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'));
const engineSource = fs.readFileSync(path.join(repoRoot, 'engine.js'), 'utf8');
const apiSource = fs.readFileSync(path.join(repoRoot, 'sdk', 'api.js'), 'utf8');
const typesSource = fs.readFileSync(path.join(repoRoot, 'sdk', 'types.d.ts'), 'utf8');
const snapshotSource = fs.readFileSync(path.join(repoRoot, 'data', 'localmaxxing-snapshot.js'), 'utf8');
const version = pkg.version;

const snapshotContext = { window: {} };
vm.createContext(snapshotContext);
vm.runInContext(snapshotSource, snapshotContext);
const snapshot = snapshotContext.window.LOCALMAXXING_SNAPSHOT;
const evidence = { generatedAt: snapshot.generatedAt, source: snapshot.source, goldCases: snapshot.goldCases };

const indent = source => source.split('\n').map(line => (line ? `    ${line}` : line)).join('\n');

const factoryBody = `
function createEngine(options = {}) {
${indent(engineSource)}
${indent(apiSource)}
    if (options.snapshot) setEngineEvidence(options.snapshot);
    const api = createApi();
    api.version = ${JSON.stringify(version)};
    api.evidenceGeneratedAt = options.snapshot?.generatedAt || null;
    return api;
}
`;

const banner = `/*! ML Bottleneck engine v${version} | https://mlbottleneck.com | MIT */`;

const esm = `${banner}
// Generated by scripts/build-sdk.mjs from engine.js and sdk/api.js. Do not edit.
${factoryBody}
const version = ${JSON.stringify(version)};
export { createEngine, version };
export default createEngine;
`;

const umd = `${banner}
// Generated by scripts/build-sdk.mjs from engine.js and sdk/api.js. Do not edit.
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define([], factory);
    } else if (typeof module === 'object' && module.exports) {
        module.exports = factory();
    } else {
        root.MLBottleneck = factory();
    }
}(typeof self !== 'undefined' ? self : this, function () {
${indent(factoryBody)}
    return { createEngine, version: ${JSON.stringify(version)} };
}));
`;

const distDir = path.join(repoRoot, 'dist');
fs.mkdirSync(distDir, { recursive: true });
fs.writeFileSync(path.join(distDir, 'mlbottleneck-engine.mjs'), esm, 'utf8');
fs.writeFileSync(path.join(distDir, 'mlbottleneck-engine.umd.js'), umd, 'utf8');
fs.writeFileSync(path.join(distDir, 'mlbottleneck-engine.d.ts'), typesSource, 'utf8');
fs.writeFileSync(path.join(distDir, 'localmaxxing-snapshot.json'), JSON.stringify(evidence), 'utf8');
fs.writeFileSync(path.join(distDir, 'package.json'), JSON.stringify({
    name: '@mlbottleneck/engine',
    version,
    description: 'Physics-based LLM inference planner: decode/prefill token rates, memory fit, and bottlenecks for any model on any hardware.',
    license: 'MIT',
    homepage: 'https://mlbottleneck.com',
    repository: 'github:steveseguin/ml-bottleneck',
    // No "type": the .js UMD build is CommonJS-compatible, the .mjs is ESM.
    main: './mlbottleneck-engine.umd.js',
    module: './mlbottleneck-engine.mjs',
    types: './mlbottleneck-engine.d.ts',
    exports: {
        '.': { import: './mlbottleneck-engine.mjs', require: './mlbottleneck-engine.umd.js', types: './mlbottleneck-engine.d.ts' },
        './snapshot': './localmaxxing-snapshot.json'
    },
    files: ['mlbottleneck-engine.mjs', 'mlbottleneck-engine.umd.js', 'mlbottleneck-engine.d.ts', 'localmaxxing-snapshot.json']
}, null, 2), 'utf8');

// Smoke: the strict-mode ESM wrapper must evaluate and predict.
const smokeContext = { console };
vm.createContext(smokeContext);
vm.runInContext(`'use strict';\n${factoryBody}\nglobalThis.__engine = createEngine();`, smokeContext, { filename: 'mlbottleneck-engine.smoke.js' });
const engine = smokeContext.__engine;
const smoke = engine.predict({ model: 'llama3_8b', hardware: 'RTX 4090', quantization: 'q4', runtime: 'llama_cpp' });
if (!(smoke.decode.tokensPerSecond > 50 && smoke.decode.tokensPerSecond < 250)) {
    throw new Error(`SDK smoke prediction out of range: ${JSON.stringify(smoke.decode)}`);
}
console.log(`SDK v${version} built: ${Math.round(esm.length / 1024)} KB ESM, ${Math.round(umd.length / 1024)} KB UMD, ${evidence.goldCases.length} evidence rows; smoke llama3_8b/4090 = ${smoke.decode.tokensPerSecond} tok/s`);
